[package]
name = "paystreamer_v2"
version = "2.0.0"
edition = "2024.beta"

[dependencies]
openzeppelin_access = { git = "https://github.com/OpenZeppelin/contracts-sui.git", subdir = "contracts/access", rev = "a116bf757c075a6404e57bb14003b233fb2a912b" }
openzeppelin_utils = { git = "https://github.com/OpenZeppelin/contracts-sui.git", subdir = "contracts/utils", rev = "a116bf757c075a6404e57bb14003b233fb2a912b" }
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "367fd808279bed26f7c64fc63160062a2ee29ab7", override = true }
MoveStdlib = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/move-stdlib", rev = "367fd808279bed26f7c64fc63160062a2ee29ab7", override = true }

[addresses]
paystreamer_v2 = "0x0"
