[package]
name = "stablecoin"
version = "0.0.1"
edition = "2024"

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "718ae563a42fb4ba0d055588f81c704dcef58c25" }

[addresses]
stablecoin = "0x0"

[environments]
devnet = "5ea2c653"
localnet = "5ea2c653"