packages:
  - 'packages/*'
  - 'apps/*'
allowBuilds:
  '@swc/core': true
  esbuild: true
  protobufjs: true
minimumReleaseAgeExclude:
  - '@paystreamer/sdk@0.1.0'
overrides:
  '@headlessui/react': '^2.2.0'
